### ISSUE TITLE
Set up user(s) on Wix

### ISSUE THREAD

**Issue by jayhill** [CodeWithAsheville/sunrise-site#11]
As best I can tell, each person contributing on this project can do so with their own Wix account, but will need to be configured with permissions by an administrator.

The administrator may be someone with Sunrise AVL or they may have the Code for Asheville project lead do this on their behalf. In the latter case, the project lead should coordinate with folks at Sunrise to get themselves set up with the `Website Manager` role.

I think contributors should have the `Website Designer` role.

From the [docs](https://support.wix.com/en/article/roles-permissions-overview): 
![image](https://user-images.githubusercontent.com/116148/114067439-d1475380-986a-11eb-9440-e0abff1bf0b4.png)

**Comment by agirlnamedsophia** [comment]
Created a site manager for myself but should ensure to pass this off to someone else who wants to contribute when I go on mat leave in a few weeks.
