### ISSUE TITLE
Provide training to Sunrise folks

### ISSUE THREAD

**Issue by jayhill** [CodeWithAsheville/sunrise-site#12]
Provide some training with Sunrise folks on how to update their Wix site, going forward.

**Comment by vakowal** [comment]
Sophia handed over the reins for this project to me, as a member of both Code for Avl and Sunrise, on June 17. She got me oriented to the website and showed me around the changes left to make. I have been able to find my way around Wix so far!  I think we can consider this training complete.

And with that, I think we can probably consider this Code for Avl project complete, too. 🎉

**Comment by jayhill** [comment]
Thank you so much, @vakowal and @agirlnamedsophia! 🎉
