### ISSUE TITLE
Prepare and execute project MoU with Sunrise AVL

### ISSUE THREAD

**Issue by jayhill** [CodeWithAsheville/sunrise-site#13]

**Comment by vakowal** [comment]
I'm ignorant and curious about the status of this MoU. Given that the two folks who were most likely involved with it (Sophia from Code For Avl and Alex from Sunrise) have very limited capacity at the moment, I'm hesitant to pester them to ask about it.

**Comment by jayhill** [comment]
Yeah, it was aspirational and on me; I never followed through with it.
I'll go ahead and close this one. Thanks!
